
= Steps to fix

. Backup zen and spark databases
+
.. Backup metastore db data
+
[source,bash]
----
CPD_NAMESPACE=zen
oc exec -it  zen-metastoredb-1 bash -n $CPD_NAMESPACE
cp -r /certs/ /tmp/
cd /tmp/ && chmod -R  0700 certs/
cd  /cockroach
./cockroach dump zen --certs-dir=/tmp/certs/ --host=zen-metastoredb-1.zen-metastoredb > /tmp/zen_backup.sql
./cockroach dump spark --certs-dir=/tmp/certs/ --host=zen-metastoredb-1.zen-metastoredb > /tmp/spark_backup.sql
exit

----
+
.. Copy backup to host folder
+
[source,bash]
----
oc cp $CPD_NAMESPACE/zen-metastoredb-1:/tmp/zen_backup.sql /root/rstemp/tmp/zen_backup.sql
oc cp $CPD_NAMESPACE/zen-metastoredb-1:/tmp/spark_backup.sql /root/rstemp/tmp/spark_backup.sql

----

.. Backup resources
+
[source,bash]
----
oc get statefulset zen-metastoredb -o yaml > zen-metastoredb.yaml
cp -p zen-metastoredb.yaml zen-metastoredb.yaml.org

oc get jobs zen-metastoredb-init -o yaml > zen-metastoredb-init.yaml
cp -p zen-metastoredb-init.yaml zen-metastoredb-init.yaml.org

oc get secret metastore-secret -o yaml > metastore-secret.yaml
cp -p metastore-secret.yaml metastore-secret.yaml.org
----

. Check cockroach node status from zen-metastoredb-1
+
[source,bash]
----

oc rsh zen-metastoredb-1 bash
Defaulted container "zen-metastoredb" out of: zen-metastoredb, init-container (init)

./cockroach node status --certs-dir=/tmp/certs/ --host=zen-metastoredb-1.zen-metastoredb
id |                 address                 |               sql_address               |  build   |            started_at            |            updated_at            | locality | is_available | is_live
-----+-----------------------------------------+-----------------------------------------+----------+----------------------------------+----------------------------------+----------+--------------+----------
1 | zen-metastoredb-1.zen-metastoredb:26257 | zen-metastoredb-1.zen-metastoredb:26257 | v20.1.12 | 2021-10-20 17:50:43.712803+00:00 | 2021-10-21 07:57:51.324714+00:00 |          | true         | true
2 | zen-metastoredb-0.zen-metastoredb:26257 | zen-metastoredb-0.zen-metastoredb:26257 | v20.1.12 | 2021-10-20 20:14:45.68699+00:00  | 2021-10-20 17:50:50.160529+00:00 |          | false        | true
3 | zen-metastoredb-2.zen-metastoredb:26257 | zen-metastoredb-2.zen-metastoredb:26257 | v20.1.12 | 2021-10-20 17:50:39.830967+00:00 | 2021-10-21 07:57:52.020486+00:00 |          | true         | true
(3 rows)

----

. Scale down zen-metastoredb statefulset to 0
+
[source,bash]
----
oc scale sts zen-metastoredb --replicas=0
----

. Delete PVC datadir-zen-metastoredb-0
+
[source,bash]
----
oc delete pvc datadir-zen-metastoredb-0
----


. Scale up zen-metastoredb statefulset to 3
+
[source,bash]
----
oc scale sts zen-metastoredb --replicas=3
----


. Wait until all pods are up
+
[source,bash]
----
oc get po -o wide | grep -e NAME -e metastore
NAME                                                 READY   STATUS      RESTARTS   AGE     IP             NODE                          NOMINATED NODE   READINESS GATES
zen-metastoredb-0                                    1/1     Running     0          5m5s    10.129.3.35    cluster6-p4cqg-worker-fbp5g   <none>           <none>
zen-metastoredb-1                                    1/1     Running     0          5m5s    10.130.3.50    cluster6-p4cqg-worker-8wflp   <none>           <none>
zen-metastoredb-2                                    1/1     Running     0          5m5s    10.130.3.51    cluster6-p4cqg-worker-8wflp   <none>           <none>

----

. Remove old dead cockroach node to avoid collecting stats and check cockroach node status

+
[source,bash]
----
oc rsh zen-metastoredb-1 bash
Defaulted container "zen-metastoredb" out of: zen-metastoredb, init-container (init)

bash-4.4$ ./cockroach node status --certs-dir=/tmp/certs/ --host=zen-metastoredb-1.zen-metastoredb
id |                 address                 |               sql_address               |  build   |            started_at            |            updated_at            | locality | is_available | is_live
-----+-----------------------------------------+-----------------------------------------+----------+----------------------------------+----------------------------------+----------+--------------+----------
1 | zen-metastoredb-1.zen-metastoredb:26257 | zen-metastoredb-1.zen-metastoredb:26257 | v20.1.12 | 2021-10-21 12:04:34.69337+00:00  | 2021-10-21 12:23:37.841289+00:00 |          | true         | true
2 | NULL                                    | NULL                                    | NULL     | NULL                             | 2021-10-21 12:04:40.268418+00:00 | NULL     | false        | false
3 | zen-metastoredb-2.zen-metastoredb:26257 | zen-metastoredb-2.zen-metastoredb:26257 | v20.1.12 | 2021-10-21 12:04:34.68365+00:00  | 2021-10-21 12:23:37.841404+00:00 |          | true         | true
4 | zen-metastoredb-0.zen-metastoredb:26257 | zen-metastoredb-0.zen-metastoredb:26257 | v20.1.12 | 2021-10-21 12:04:41.030687+00:00 | 2021-10-21 12:23:39.60273+00:00  |          | true         | true
(4 rows)

----

+
[source,bash]
----
bash-4.4$ ./cockroach node decommission 2 --certs-dir=/tmp/certs/ --host=zen-metastoredb-1.zen-metastoredb

id | is_live | replicas | is_decommissioning | is_draining
-----+---------+----------+--------------------+--------------
2 |  false  |        0 |        true        |    false
(1 row)

No more data reported on target nodes. Please verify cluster health before removing the nodes.

----

+
[source,bash]
----
bash-4.4$ ./cockroach node status --certs-dir=/tmp/certs/ --host=zen-metastoredb-1.zen-metastoredb
id |                 address                 |               sql_address               |  build   |            started_at            |            updated_at            | locality | is_available | is_live
-----+-----------------------------------------+-----------------------------------------+----------+----------------------------------+----------------------------------+----------+--------------+----------
1 | zen-metastoredb-1.zen-metastoredb:26257 | zen-metastoredb-1.zen-metastoredb:26257 | v20.1.12 | 2021-10-21 12:04:34.69337+00:00  | 2021-10-21 12:24:22.847248+00:00 |          | true         | true
3 | zen-metastoredb-2.zen-metastoredb:26257 | zen-metastoredb-2.zen-metastoredb:26257 | v20.1.12 | 2021-10-21 12:04:34.68365+00:00  | 2021-10-21 12:24:22.847537+00:00 |          | true         | true
4 | zen-metastoredb-0.zen-metastoredb:26257 | zen-metastoredb-0.zen-metastoredb:26257 | v20.1.12 | 2021-10-21 12:04:41.030687+00:00 | 2021-10-21 12:24:20.102434+00:00 |          | true         | true
(3 rows)

----

. Check POD status
+
[source,bash]
----

oc get po -o wide | grep -e NAME -e metastore
NAME                                                 READY   STATUS      RESTARTS   AGE     IP             NODE                          NOMINATED NODE   READINESS GATES
zen-metastoredb-0                                    1/1     Running     0          24m     10.129.3.35    cluster6-p4cqg-worker-fbp5g   <none>           <none>
zen-metastoredb-1                                    1/1     Running     0          24m     10.130.3.50    cluster6-p4cqg-worker-8wflp   <none>           <none>
zen-metastoredb-2                                    1/1     Running     0          24m     10.130.3.51    cluster6-p4cqg-worker-8wflp   <none>           <none>

----
